### ISSUE TITLE
Error loading ArtFlowNet

### ISSUE THREAD

**Issue by raabuchanan** [r-pad/flowbot3d#32]
Hello,
I managed to install the python packages but when I try to load to the model in python with

`from flowbot3d.models.artflownet import ArtFlowNet`

I get the following error related to `rpad.pyg.nets.pointnet2`

```
(flowbot) russell@robot-System-Product-Name:~$ python3
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from flowbot3d.models.artflownet import ArtFlowNet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/russell/git/flowbot3d/flowbot3d/models/artflownet.py", line 7, in <module>
    import rpad.pyg.nets.pointnet2 as pnp
  File "/home/russell/.local/lib/python3.8/site-packages/rpad/pyg/nets/pointnet2.py", line 8, in <module>
    from torch_geometric.nn import PointConv, fps, global_max_pool, knn_interpolate, radius
ImportError: cannot import name 'PointConv' from 'torch_geometric.nn' (/home/russell/.local/lib/python3.8/site-packages/torch_geometric/nn/__init__.py)
```

**Comment by beneisner** [comment]
Hi - I believe they may have renamed PointConv -> PointNetConv; which version of pytorch geometric are you using? 

Regardless, I believe that the alias should still work: https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/nn/conv/__init__.py#L135


since torch_geometric.nn imports everything: https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/nn/__init__.py

**Comment by beneisner** [comment]
OK yeah I am able to reproduce this. I'll make a fix to the repo, either:
1. pinning the version of torch geometric to being lower (likely, because I don't want to change other functionality inadvertently)
2. changing the name of the import.

**Comment by beneisner** [comment]
Yeah if you downgrade torch geometric to < 2.3, it works:

```
pip install torch_geometric==2.2.0
```
